# default config

#time to wait between each random joke in seconds
timeBetweenJokes: 300

#the jokes themselves
jokes:
 - It's sad that a family can be torn apart by something as simple as wild dogs.
 - If trees could scream would we still cut them down? We might, if they did it all the time for no good reason.
 - The face of a child can say it all, especially the mouth part of the face.
 - I don't like cocaine, I just like the way it smells.
 - Childhood is like being drunk, everyone remembers what you did, except you.
 - I have a parrot and it talks. But it did not say it was hungry, so it died.
 - Dogs are always in the push-up position.
 - Throwing acid is wrong, in some people's eyes.
 - No matter how much you give a homeless person for tea... you never get that tea.
 - When I was younger my dad used to beat me with a camera. I still have flashbacks...and a really weird photo album.
 - Somebody stole my mood rings, and I don't know how I feel about that.
 - A Freudian slip is when you mean one thing but fuck your mother.
 - I can tell how much my parents loved me by the memory that my favourite bath toy as a child was a toaster.
 - If four out of five people suffer from diarrhea, does that mean there's one person who enjoys it?
 - Last night I stayed up late and played poker with tarot cards, i got a full house and six people died.
 - I put instant coffee in a microwave and I almost went back in time.
 - Some people are afraid of heights. I'm afraid of widths.
 - If your girlfriend starts smoking, slow down and use a lubricant.
 - Time flies like an arrow, fruit flies like a banana.
 - Every time I have sex with a woman I always assume she has herpes, that way I don't have to tell her about mine.
 - It takes a lot of balls to golf the way I do.
 - My grandfather has the heart of a lion, and a lifetime ban from the zoo.
 - Together, I can beat dissociative identity.
 - Standard deviation not enough for perverted statistician.
 - Anytime I see an autobiography on the shelf I just skip to the about the author section.
 - Outside of a dog, a man's best friend is a book; inside of a dog, it's too dark to read.
 - No matter how good I get at tennis, I'll never be as good as a wall.
 - A banana is like a reverse stop light. Green means wait. Yellow means go ahead. Red means where the fuck did you get that banana?
 - A duck's opinion of you is directly correlated to whether or not you have bread.
 - I always believe that someone else on the planet is shaving, so whenever I shave I always say I'm gonna go shave too.
 - Burritos are like sleeping bags for ground beef.
 - Weather forecast for tonight: dark.
 - It’s never just a game when you’re winning.
 - Fighting for peace is like screwing for virginity.
 - Well, if crime fighters fight crime and fire fighters fight fire, what do freedom fighters fight? They never mention that part to us, do they?
 - Have you ever noticed that anybody driving slower than you is an idiot, and anyone going faster than you is a maniac?
 - One tequila, two tequila, three tequila, floor.
 - The reason I talk to myself is that I am the only one whose answers I accept.
 - THINGS YOU NEVER HEAR Please stop sucking my dick or I will call the police.
 - Once you leave out all the bullshit they teach you in school, life gets really simple.